* Práctica 2.5 - Personalización de Estilos mediante Media Queries
** Introducción
El objetivo de esta práctica es utilizar Media Queries para personalizar la apariencia del formulario web desarrollado en la práctica 2.4 en función del tamaño de la pantalla del dispositivo.
** Tiempo asignado
2 horas de clase
** Material de la práctica
Para realizar la práctica se tomará como base los archivos creados en la práctica 2.4 (HTML y CSS).
** Desarrollo de la práctica
Se debe modificar el código CSS del formulario creado en la práctica 2.4 para que el aspecto visual sea el indicado en función del tipo de dispositivo. Debes elegir una resolución apropiada para cada dispositivo (no hace falta que sea exacta al 100%).
*** Dispositivos móviles
*** Tabletas
*** Ordenadores
** Resultado a entregar
- Se deberá realizar una /pull request/ al respositorio de la práctica (https://github.com/interfacesweb/practica_2_5) con el código completo del formulario (HTML y CSS).
- En el comentario de la /pull request/ se deberá incluir el *nombre y apellidos* del alumno.
